# Base image
FROM node:14

# Set working directory
WORKDIR /usr/src/app

# Copy package.json and package-lock.json
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of the application code
COPY . .

# Expose the API server port
EXPOSE 3000

# Command to run the Nest.js API server
CMD ["npm", "run", "start:prod"]
